# NumPy Work

In [1]:
import numpy as np

zeromatrix = np.zeros(shape=(3,3))
print (zeromatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Matrix Multiplication

In [8]:
import numpy as np

A = np.array([
    [1,2,3],
    [4,5,6]
])

B = np.array([
    [2,3,4],
    [5,6,7],
    [3,2,1]
])

print(np.dot(A,B))
print(np.matmul(A,B))
print(3 * A)
print(A @ B)

[[21 21 21]
 [51 54 57]]
[[21 21 21]
 [51 54 57]]
[[ 3  6  9]
 [12 15 18]]
[[21 21 21]
 [51 54 57]]
